/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactPerson } from './contactPerson';

/**
 * Agency
 */
export interface Agentur {
  /**
   * address
   */
  adresse?: string;
  ansprechpartner?: ContactPerson;
  /**
   * fax number
   */
  faxnummer?: string;
  /**
   * house number (part of the address)
   */
  hausnummer?: string;
  /**
   * name
   */
  name: string;
  /**
   * city
   */
  ort?: string;
  /**
   * zip
   */
  plz?: string;
  /**
   * phone number
   */
  telefonnummer?: string;
  emailAdresse?: string;
}

