/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Mitteilung } from './mitteilung';

export interface Anliegen {
  /**
   * date as String: yyyy-MM-dd\'T\'HH:mm:ssZ
   */
  closedAt: string;
  /**
   * true if anliegen is answered, null if automatically closed, else false
   */
  anliegenHasAnswer?: boolean;
  anliegenNr: string;
  antwortKanalLabel?: string;
  /**
   * chanel over which answer was provided to client
   */
  antwortKanal?: Anliegen.AntwortKanalEnum;
  rating?: string;
  ratingFeedback?: string;
  readyForAnswer?: boolean;
  readyForRating?: boolean;
  /**
   * chanel over which anliegen was submitted to the insurance company
   */
  eingangsKanal: Anliegen.EingangsKanalEnum;
  /**
   * chanel over which anliegen was submitted to the insurance company
   */
  eingangsKanalLabel: string;
  /**
   * date as String: yyyy-MM-dd\'T\'HH:mm:ssZ
   */
  creationDate: string;
  /**
   * messages
   */
  mitteilungen?: Array<Mitteilung>;
  statusLabel?: string;
  status: Anliegen.StatusEnum;
  taetigkeitLabel: string;
  /**
   * topic of anliegen
   */
  taetigkeit: Anliegen.TaetigkeitEnum;
  personnelNumberEmployeeInCharge: string;
  /**
   * date as String: yyyy-MM-dd\'T\'HH:mm:ssZ
   */
  toBeAnsweredUntil: string;
  /**
   * true if anliegen can be reopened
   */
  canBeReopened?: boolean;
}
export namespace Anliegen {
    export type AntwortKanalEnum = 'APP' | 'AUSWERTUNG' | 'BENUTZER' | 'BRIEF' | 'CHAT' | 'DRUCKOUTPUT' | 'EBUSINESS' | 'ELEKTRONISCHER_DATENAUSTAUSCH' | 'EMAIL' | 'ERROR_QUEUE' | 'FAX' | 'INBOUND' | 'INTERN' | 'INTERNET' | 'MESSENGER' | 'OUTBOUND' | 'PERSOENLICH' | 'PORTAL' | 'SCANNING' | 'SEDEX' | 'SOCIAL_MEDIA' | 'TELEFONIE';
    export const AntwortKanalEnum = {
        APP: 'APP' as AntwortKanalEnum,
        AUSWERTUNG: 'AUSWERTUNG' as AntwortKanalEnum,
        BENUTZER: 'BENUTZER' as AntwortKanalEnum,
        BRIEF: 'BRIEF' as AntwortKanalEnum,
        CHAT: 'CHAT' as AntwortKanalEnum,
        DRUCKOUTPUT: 'DRUCKOUTPUT' as AntwortKanalEnum,
        EBUSINESS: 'EBUSINESS' as AntwortKanalEnum,
        ELEKTRONISCHERDATENAUSTAUSCH: 'ELEKTRONISCHER_DATENAUSTAUSCH' as AntwortKanalEnum,
        EMAIL: 'EMAIL' as AntwortKanalEnum,
        ERRORQUEUE: 'ERROR_QUEUE' as AntwortKanalEnum,
        FAX: 'FAX' as AntwortKanalEnum,
        INBOUND: 'INBOUND' as AntwortKanalEnum,
        INTERN: 'INTERN' as AntwortKanalEnum,
        INTERNET: 'INTERNET' as AntwortKanalEnum,
        MESSENGER: 'MESSENGER' as AntwortKanalEnum,
        OUTBOUND: 'OUTBOUND' as AntwortKanalEnum,
        PERSOENLICH: 'PERSOENLICH' as AntwortKanalEnum,
        PORTAL: 'PORTAL' as AntwortKanalEnum,
        SCANNING: 'SCANNING' as AntwortKanalEnum,
        SEDEX: 'SEDEX' as AntwortKanalEnum,
        SOCIALMEDIA: 'SOCIAL_MEDIA' as AntwortKanalEnum,
        TELEFONIE: 'TELEFONIE' as AntwortKanalEnum
    };
    export type EingangsKanalEnum = 'APP' | 'AUSWERTUNG' | 'BENUTZER' | 'BRIEF' | 'CHAT' | 'DRUCKOUTPUT' | 'EBUSINESS' | 'ELEKTRONISCHER_DATENAUSTAUSCH' | 'EMAIL' | 'ERROR_QUEUE' | 'FAX' | 'INBOUND' | 'INTERN' | 'INTERNET' | 'MESSENGER' | 'OUTBOUND' | 'PERSOENLICH' | 'PORTAL' | 'SCANNING' | 'SEDEX' | 'SOCIAL_MEDIA' | 'TELEFONIE';
    export const EingangsKanalEnum = {
        APP: 'APP' as EingangsKanalEnum,
        AUSWERTUNG: 'AUSWERTUNG' as EingangsKanalEnum,
        BENUTZER: 'BENUTZER' as EingangsKanalEnum,
        BRIEF: 'BRIEF' as EingangsKanalEnum,
        CHAT: 'CHAT' as EingangsKanalEnum,
        DRUCKOUTPUT: 'DRUCKOUTPUT' as EingangsKanalEnum,
        EBUSINESS: 'EBUSINESS' as EingangsKanalEnum,
        ELEKTRONISCHERDATENAUSTAUSCH: 'ELEKTRONISCHER_DATENAUSTAUSCH' as EingangsKanalEnum,
        EMAIL: 'EMAIL' as EingangsKanalEnum,
        ERRORQUEUE: 'ERROR_QUEUE' as EingangsKanalEnum,
        FAX: 'FAX' as EingangsKanalEnum,
        INBOUND: 'INBOUND' as EingangsKanalEnum,
        INTERN: 'INTERN' as EingangsKanalEnum,
        INTERNET: 'INTERNET' as EingangsKanalEnum,
        MESSENGER: 'MESSENGER' as EingangsKanalEnum,
        OUTBOUND: 'OUTBOUND' as EingangsKanalEnum,
        PERSOENLICH: 'PERSOENLICH' as EingangsKanalEnum,
        PORTAL: 'PORTAL' as EingangsKanalEnum,
        SCANNING: 'SCANNING' as EingangsKanalEnum,
        SEDEX: 'SEDEX' as EingangsKanalEnum,
        SOCIALMEDIA: 'SOCIAL_MEDIA' as EingangsKanalEnum,
        TELEFONIE: 'TELEFONIE' as EingangsKanalEnum
    };
    export type StatusEnum = 'ABGESCHLOSSEN' | 'ANNULIERT' | 'EINGEREICHT' | 'INBEARBEITUNG';
    export const StatusEnum = {
        ABGESCHLOSSEN: 'ABGESCHLOSSEN' as StatusEnum,
        ANNULIERT: 'ANNULIERT' as StatusEnum,
        EINGEREICHT: 'EINGEREICHT' as StatusEnum,
        INBEARBEITUNG: 'INBEARBEITUNG' as StatusEnum
    };
    export type TaetigkeitEnum = 'ADRESSAENDERUNG' | 'AENDERUNG_GEBURTSJAHR' | 'AENDERUNG_KUNDENDATEN' | 'AENDERUNG_KUNDENDATEN_FAMILIE' | 'AENDERUNG_LEISTUNGSFREIHEITSRABATT' | 'AENDERUNG_VERTRAGSDAUER' | 'AENDERUNG_ZAHLUNGSVERBINDUNG' | 'ANBIETERWECHSEL' | 'ANFRAGE_AUSZAHULUNG' | 'ANFRAGE_BETREUUNGSPROGRAMM' | 'ANFRAGE_INKASSO' | 'ANFRAGE_LEISTUNG_IHP' | 'ANFRAGE_MAHNUNGEN' | 'ANFRAGE_MEDGATE' | 'ANFRAGE_MYCSS' | 'ANFRAGE_MYSTEP' | 'ANFRAGE_PRAEMIENVERBILLIGUNG' | 'ANFRAGE_SERVICE_IHP' | 'ANFRAGE_ZAHLUNGSEINGANG' | 'ANLIEGEN' | 'ANTRAGSENTSCHEID' | 'ANTRAGSPRUEFUNG' | 'ANZEIGEPFLICHTVERLETZUNG' | 'AUSWANDERUNG' | 'BESTELLUNG_LSV_FORMULAR' | 'BESTELLUNG_SCHADENANZEIGE' | 'BESTELLUNG_STEUERAUSZUG' | 'BESTELLUNG_STILLGELDAUSWEIS' | 'BESTELLUNG_UEBERWEISUNGSFORMULAR' | 'BESTELLUNG_VERSICHERUNGSKARTE' | 'BESTELLUNG_ZAHNSCHADENFORMULAR' | 'DECKUNGSAENDERUNG' | 'ETIKETTENBESTELLUNG' | 'FRAGEN_KOLLEKTIVE_HEILUNGSKOSTEN' | 'GESCHLECHTSAENDERUNG' | 'HAUSARZTWECHSEL' | 'KONTOINFORMATIONEN' | 'KUENDIGUNG' | 'LEISTUNGSEINSCHRAENKUNG' | 'LEISTUNGSFRAGEN' | 'MILITAERSISTIERUNG' | 'MITGLIEDSCHAFT_CSS_VEREIN' | 'PRAN_TALON' | 'PRODUKTBERATUNG' | 'RECHNUNGSAENDERUNG' | 'RECHNUNGSAUSKUNFT' | 'RECHTSDIENSTABKLAERUNG' | 'SISTIERUNG_ZUSATZVERSICHERUNG' | 'STEUERAUSZUG_ABBESTELLEN' | 'S_ADRESSAENDERUNG' | 'S_AENDERUNG_KUNDENDATEN' | 'S_AENDERUNG_KUNDENDATEN_FAM' | 'S_AENDERUNG_ZV' | 'S_ALLGEMEINES_ANLIEGEN' | 'S_ANFRAGE_MYSANAGATE' | 'S_ANLIEGEN_POLICE' | 'S_ANLIEGEN_PRAMIE' | 'S_BESTELLUNG_STEUERAUSZUG' | 'S_LEISTUNGSFRAGEN' | 'S_VORGEBURTLICHE_ANMELDUNG' | 'TERMINVEREINBARUNG' | 'THERAPEUTENLISTEN' | 'UNFALLEIN_AUSSCHLUSS' | 'UNFALLMELDUNG' | 'UNTERLAGENBESTELLUNG' | 'VERSICHERUNGSBESTAETIGUNG' | 'VERTRAGSAENDERUNG' | 'VERTRAGSAUFLOESUNG_TODESFALL' | 'VORGEBURTLICHE_ANMELDUNG';
    export const TaetigkeitEnum = {
        ADRESSAENDERUNG: 'ADRESSAENDERUNG' as TaetigkeitEnum,
        AENDERUNGGEBURTSJAHR: 'AENDERUNG_GEBURTSJAHR' as TaetigkeitEnum,
        AENDERUNGKUNDENDATEN: 'AENDERUNG_KUNDENDATEN' as TaetigkeitEnum,
        AENDERUNGKUNDENDATENFAMILIE: 'AENDERUNG_KUNDENDATEN_FAMILIE' as TaetigkeitEnum,
        AENDERUNGLEISTUNGSFREIHEITSRABATT: 'AENDERUNG_LEISTUNGSFREIHEITSRABATT' as TaetigkeitEnum,
        AENDERUNGVERTRAGSDAUER: 'AENDERUNG_VERTRAGSDAUER' as TaetigkeitEnum,
        AENDERUNGZAHLUNGSVERBINDUNG: 'AENDERUNG_ZAHLUNGSVERBINDUNG' as TaetigkeitEnum,
        ANBIETERWECHSEL: 'ANBIETERWECHSEL' as TaetigkeitEnum,
        ANFRAGEAUSZAHULUNG: 'ANFRAGE_AUSZAHULUNG' as TaetigkeitEnum,
        ANFRAGEBETREUUNGSPROGRAMM: 'ANFRAGE_BETREUUNGSPROGRAMM' as TaetigkeitEnum,
        ANFRAGEINKASSO: 'ANFRAGE_INKASSO' as TaetigkeitEnum,
        ANFRAGELEISTUNGIHP: 'ANFRAGE_LEISTUNG_IHP' as TaetigkeitEnum,
        ANFRAGEMAHNUNGEN: 'ANFRAGE_MAHNUNGEN' as TaetigkeitEnum,
        ANFRAGEMEDGATE: 'ANFRAGE_MEDGATE' as TaetigkeitEnum,
        ANFRAGEMYCSS: 'ANFRAGE_MYCSS' as TaetigkeitEnum,
        ANFRAGEMYSTEP: 'ANFRAGE_MYSTEP' as TaetigkeitEnum,
        ANFRAGEPRAEMIENVERBILLIGUNG: 'ANFRAGE_PRAEMIENVERBILLIGUNG' as TaetigkeitEnum,
        ANFRAGESERVICEIHP: 'ANFRAGE_SERVICE_IHP' as TaetigkeitEnum,
        ANFRAGEZAHLUNGSEINGANG: 'ANFRAGE_ZAHLUNGSEINGANG' as TaetigkeitEnum,
        ANLIEGEN: 'ANLIEGEN' as TaetigkeitEnum,
        ANTRAGSENTSCHEID: 'ANTRAGSENTSCHEID' as TaetigkeitEnum,
        ANTRAGSPRUEFUNG: 'ANTRAGSPRUEFUNG' as TaetigkeitEnum,
        ANZEIGEPFLICHTVERLETZUNG: 'ANZEIGEPFLICHTVERLETZUNG' as TaetigkeitEnum,
        AUSWANDERUNG: 'AUSWANDERUNG' as TaetigkeitEnum,
        BESTELLUNGLSVFORMULAR: 'BESTELLUNG_LSV_FORMULAR' as TaetigkeitEnum,
        BESTELLUNGSCHADENANZEIGE: 'BESTELLUNG_SCHADENANZEIGE' as TaetigkeitEnum,
        BESTELLUNGSTEUERAUSZUG: 'BESTELLUNG_STEUERAUSZUG' as TaetigkeitEnum,
        BESTELLUNGSTILLGELDAUSWEIS: 'BESTELLUNG_STILLGELDAUSWEIS' as TaetigkeitEnum,
        BESTELLUNGUEBERWEISUNGSFORMULAR: 'BESTELLUNG_UEBERWEISUNGSFORMULAR' as TaetigkeitEnum,
        BESTELLUNGVERSICHERUNGSKARTE: 'BESTELLUNG_VERSICHERUNGSKARTE' as TaetigkeitEnum,
        BESTELLUNGZAHNSCHADENFORMULAR: 'BESTELLUNG_ZAHNSCHADENFORMULAR' as TaetigkeitEnum,
        DECKUNGSAENDERUNG: 'DECKUNGSAENDERUNG' as TaetigkeitEnum,
        ETIKETTENBESTELLUNG: 'ETIKETTENBESTELLUNG' as TaetigkeitEnum,
        FRAGENKOLLEKTIVEHEILUNGSKOSTEN: 'FRAGEN_KOLLEKTIVE_HEILUNGSKOSTEN' as TaetigkeitEnum,
        GESCHLECHTSAENDERUNG: 'GESCHLECHTSAENDERUNG' as TaetigkeitEnum,
        HAUSARZTWECHSEL: 'HAUSARZTWECHSEL' as TaetigkeitEnum,
        KONTOINFORMATIONEN: 'KONTOINFORMATIONEN' as TaetigkeitEnum,
        KUENDIGUNG: 'KUENDIGUNG' as TaetigkeitEnum,
        LEISTUNGSEINSCHRAENKUNG: 'LEISTUNGSEINSCHRAENKUNG' as TaetigkeitEnum,
        LEISTUNGSFRAGEN: 'LEISTUNGSFRAGEN' as TaetigkeitEnum,
        MILITAERSISTIERUNG: 'MILITAERSISTIERUNG' as TaetigkeitEnum,
        MITGLIEDSCHAFTCSSVEREIN: 'MITGLIEDSCHAFT_CSS_VEREIN' as TaetigkeitEnum,
        PRANTALON: 'PRAN_TALON' as TaetigkeitEnum,
        PRODUKTBERATUNG: 'PRODUKTBERATUNG' as TaetigkeitEnum,
        RECHNUNGSAENDERUNG: 'RECHNUNGSAENDERUNG' as TaetigkeitEnum,
        RECHNUNGSAUSKUNFT: 'RECHNUNGSAUSKUNFT' as TaetigkeitEnum,
        RECHTSDIENSTABKLAERUNG: 'RECHTSDIENSTABKLAERUNG' as TaetigkeitEnum,
        SISTIERUNGZUSATZVERSICHERUNG: 'SISTIERUNG_ZUSATZVERSICHERUNG' as TaetigkeitEnum,
        STEUERAUSZUGABBESTELLEN: 'STEUERAUSZUG_ABBESTELLEN' as TaetigkeitEnum,
        SADRESSAENDERUNG: 'S_ADRESSAENDERUNG' as TaetigkeitEnum,
        SAENDERUNGKUNDENDATEN: 'S_AENDERUNG_KUNDENDATEN' as TaetigkeitEnum,
        SAENDERUNGKUNDENDATENFAM: 'S_AENDERUNG_KUNDENDATEN_FAM' as TaetigkeitEnum,
        SAENDERUNGZV: 'S_AENDERUNG_ZV' as TaetigkeitEnum,
        SALLGEMEINESANLIEGEN: 'S_ALLGEMEINES_ANLIEGEN' as TaetigkeitEnum,
        SANFRAGEMYSANAGATE: 'S_ANFRAGE_MYSANAGATE' as TaetigkeitEnum,
        SANLIEGENPOLICE: 'S_ANLIEGEN_POLICE' as TaetigkeitEnum,
        SANLIEGENPRAMIE: 'S_ANLIEGEN_PRAMIE' as TaetigkeitEnum,
        SBESTELLUNGSTEUERAUSZUG: 'S_BESTELLUNG_STEUERAUSZUG' as TaetigkeitEnum,
        SLEISTUNGSFRAGEN: 'S_LEISTUNGSFRAGEN' as TaetigkeitEnum,
        SVORGEBURTLICHEANMELDUNG: 'S_VORGEBURTLICHE_ANMELDUNG' as TaetigkeitEnum,
        TERMINVEREINBARUNG: 'TERMINVEREINBARUNG' as TaetigkeitEnum,
        THERAPEUTENLISTEN: 'THERAPEUTENLISTEN' as TaetigkeitEnum,
        UNFALLEINAUSSCHLUSS: 'UNFALLEIN_AUSSCHLUSS' as TaetigkeitEnum,
        UNFALLMELDUNG: 'UNFALLMELDUNG' as TaetigkeitEnum,
        UNTERLAGENBESTELLUNG: 'UNTERLAGENBESTELLUNG' as TaetigkeitEnum,
        VERSICHERUNGSBESTAETIGUNG: 'VERSICHERUNGSBESTAETIGUNG' as TaetigkeitEnum,
        VERTRAGSAENDERUNG: 'VERTRAGSAENDERUNG' as TaetigkeitEnum,
        VERTRAGSAUFLOESUNGTODESFALL: 'VERTRAGSAUFLOESUNG_TODESFALL' as TaetigkeitEnum,
        VORGEBURTLICHEANMELDUNG: 'VORGEBURTLICHE_ANMELDUNG' as TaetigkeitEnum
    };
}


