/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnliegenLeadTeaser { 
    /**
     * number of requests with unread messages
     */
    numberOfAnliegenWithUnreadMitteilungen: number;
    numberOfOpenAnliegen: number;
    /**
     * number of unread messages from the insurance company
     */
    numberOfUnreadMessageLeads: number;
    /**
     * total of unread messages (leads and anliegen cumulated)
     */
    numberOfUnreadMitteilungenTotal: number;
}

