/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentAccount } from './paymentAccount';

export interface BankAccount extends PaymentAccount {
  bankName?: string;
  clearingNr?: string;
  /**
   * bank account number / identifier
   */
  kontoNr?: string;
  iban: string;
  ort: string;
  postleitzahl: string;
  /**
   * discriminator: BankAccount
   */
  accountClazz: string;
}
export namespace BankAccount {
}


