/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Bewertung { 
    /**
     * rating from 1 to 10 whereas 10 is the best
     */
    rating: number;
    /**
     * datetime as String: yyyy-MM-dd\'T\'HH:mm:ssZ
     */
    createdAt: string;
    /**
     * prettyPrint: text containing html line breaks (&lt;br&gt;). Max. 3000 chars!
     */
    prettyPrint?: string;
}

