/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A particular individual whithin an agentur, who is selected as the point of initial or regular communication
 */
export interface ContactPerson { 
    /**
     * eMail address
     */
    geteMailAdresse?: string;
    /**
     * lastname
     */
    name: string;
    /**
     * internal unique identifier
     */
    personalNr: string;
    /**
     * phone number
     */
    telefonnummer?: string;
    /**
     * firstname
     */
    vorname: string;
}

