/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DokumentReferenz { 
    /**
     * file extension
     */
    dateiEndung: string;
    /**
     * datetime as String: yyyy-MM-dd
     */
    dokumentDatum: string;
    /**
     * filesize
     */
    dokumentGroesse: number;
    dokumentName?: string;
    /**
     * document identifier to load from resouce dokumentenverwaltung
     */
    dokumentNummer: string;
    /**
     * document type
     */
    dokumentTyp: DokumentReferenz.DokumentTypEnum;
    mimeType: string;
}
export namespace DokumentReferenz {
    export type DokumentTypEnum = 'ABLEHNUNG' | 'ANSCHREIBEN' | 'ANTRAG' | 'AUSTRITT' | 'AUSWERTUNG' | 'AUSZAHLUNGSBELEG' | 'BETREIBUNG' | 'COURTAGENABRECHNUNG' | 'DOKUMENT_SCHUTZ' | 'DOWNLOAD' | 'EINGANGSKORRESPONDENZ' | 'EINGANGS_DOKUMENT' | 'FORMULAR' | 'KAMPAGNE' | 'KONTOAUSZUG' | 'KORRESPONDENZ' | 'KOSTENGUTSPRACHE' | 'KUENDIGUNG' | 'LEISTUNG' | 'LEISTUNGSABRECHNUNG' | 'LEISTUNGSERBRINGER_DOKUMENT' | 'LEISTUNGSERBRINGER_VERTRAG' | 'LOHNSUMMENDEKLARATION' | 'LeaLee' | 'MAHNUNG' | 'MEDIZINISCHE_UNTERLAGEN' | 'OFFERTE' | 'POLICE' | 'PORTAL_NACHRICHT' | 'POSTRETOUREN' | 'PRAEMIENRECHNUNG' | 'PROTOCOL_DATA' | 'PROVISIONSABRECHNUNG' | 'PROZESS_DOKUMENTATION' | 'PV_SENDUNG' | 'RATENPLANVEREINBARUNG' | 'RAV_U' | 'RECHNUNG' | 'RECHNUNG_MCD' | 'RUECKLAEUFERDOKUMENT' | 'SACH_HAFTPFLICHT' | 'SANIERUNG' | 'SPITALTAGGELD' | 'SUPPORT_ANFRAGE' | 'TAGGELDBELEG' | 'TAGGELD_AUSZAHLUNGSBELEG' | 'TARIF_BLAETTER' | 'TRANSFER' | 'UEBERENTSCHAEDIGUNG' | 'UEBERSCHUSSABRECHNUNG' | 'UNFALLANZEIGE' | 'UNFALL_DOSSIER' | 'VAD_DOKUMENT' | 'VERFUEGUNG' | 'VERORDNUNG' | 'VERSICHERUNGSABSCHLUSS' | 'VERTRAGSMUTATION';
    export const DokumentTypEnum = {
        ABLEHNUNG: 'ABLEHNUNG' as DokumentTypEnum,
        ANSCHREIBEN: 'ANSCHREIBEN' as DokumentTypEnum,
        ANTRAG: 'ANTRAG' as DokumentTypEnum,
        AUSTRITT: 'AUSTRITT' as DokumentTypEnum,
        AUSWERTUNG: 'AUSWERTUNG' as DokumentTypEnum,
        AUSZAHLUNGSBELEG: 'AUSZAHLUNGSBELEG' as DokumentTypEnum,
        BETREIBUNG: 'BETREIBUNG' as DokumentTypEnum,
        COURTAGENABRECHNUNG: 'COURTAGENABRECHNUNG' as DokumentTypEnum,
        DOKUMENTSCHUTZ: 'DOKUMENT_SCHUTZ' as DokumentTypEnum,
        DOWNLOAD: 'DOWNLOAD' as DokumentTypEnum,
        EINGANGSKORRESPONDENZ: 'EINGANGSKORRESPONDENZ' as DokumentTypEnum,
        EINGANGSDOKUMENT: 'EINGANGS_DOKUMENT' as DokumentTypEnum,
        FORMULAR: 'FORMULAR' as DokumentTypEnum,
        KAMPAGNE: 'KAMPAGNE' as DokumentTypEnum,
        KONTOAUSZUG: 'KONTOAUSZUG' as DokumentTypEnum,
        KORRESPONDENZ: 'KORRESPONDENZ' as DokumentTypEnum,
        KOSTENGUTSPRACHE: 'KOSTENGUTSPRACHE' as DokumentTypEnum,
        KUENDIGUNG: 'KUENDIGUNG' as DokumentTypEnum,
        LEISTUNG: 'LEISTUNG' as DokumentTypEnum,
        LEISTUNGSABRECHNUNG: 'LEISTUNGSABRECHNUNG' as DokumentTypEnum,
        LEISTUNGSERBRINGERDOKUMENT: 'LEISTUNGSERBRINGER_DOKUMENT' as DokumentTypEnum,
        LEISTUNGSERBRINGERVERTRAG: 'LEISTUNGSERBRINGER_VERTRAG' as DokumentTypEnum,
        LOHNSUMMENDEKLARATION: 'LOHNSUMMENDEKLARATION' as DokumentTypEnum,
        LeaLee: 'LeaLee' as DokumentTypEnum,
        MAHNUNG: 'MAHNUNG' as DokumentTypEnum,
        MEDIZINISCHEUNTERLAGEN: 'MEDIZINISCHE_UNTERLAGEN' as DokumentTypEnum,
        OFFERTE: 'OFFERTE' as DokumentTypEnum,
        POLICE: 'POLICE' as DokumentTypEnum,
        PORTALNACHRICHT: 'PORTAL_NACHRICHT' as DokumentTypEnum,
        POSTRETOUREN: 'POSTRETOUREN' as DokumentTypEnum,
        PRAEMIENRECHNUNG: 'PRAEMIENRECHNUNG' as DokumentTypEnum,
        PROTOCOLDATA: 'PROTOCOL_DATA' as DokumentTypEnum,
        PROVISIONSABRECHNUNG: 'PROVISIONSABRECHNUNG' as DokumentTypEnum,
        PROZESSDOKUMENTATION: 'PROZESS_DOKUMENTATION' as DokumentTypEnum,
        PVSENDUNG: 'PV_SENDUNG' as DokumentTypEnum,
        RATENPLANVEREINBARUNG: 'RATENPLANVEREINBARUNG' as DokumentTypEnum,
        RAVU: 'RAV_U' as DokumentTypEnum,
        RECHNUNG: 'RECHNUNG' as DokumentTypEnum,
        RECHNUNGMCD: 'RECHNUNG_MCD' as DokumentTypEnum,
        RUECKLAEUFERDOKUMENT: 'RUECKLAEUFERDOKUMENT' as DokumentTypEnum,
        SACHHAFTPFLICHT: 'SACH_HAFTPFLICHT' as DokumentTypEnum,
        SANIERUNG: 'SANIERUNG' as DokumentTypEnum,
        SPITALTAGGELD: 'SPITALTAGGELD' as DokumentTypEnum,
        SUPPORTANFRAGE: 'SUPPORT_ANFRAGE' as DokumentTypEnum,
        TAGGELDBELEG: 'TAGGELDBELEG' as DokumentTypEnum,
        TAGGELDAUSZAHLUNGSBELEG: 'TAGGELD_AUSZAHLUNGSBELEG' as DokumentTypEnum,
        TARIFBLAETTER: 'TARIF_BLAETTER' as DokumentTypEnum,
        TRANSFER: 'TRANSFER' as DokumentTypEnum,
        UEBERENTSCHAEDIGUNG: 'UEBERENTSCHAEDIGUNG' as DokumentTypEnum,
        UEBERSCHUSSABRECHNUNG: 'UEBERSCHUSSABRECHNUNG' as DokumentTypEnum,
        UNFALLANZEIGE: 'UNFALLANZEIGE' as DokumentTypEnum,
        UNFALLDOSSIER: 'UNFALL_DOSSIER' as DokumentTypEnum,
        VADDOKUMENT: 'VAD_DOKUMENT' as DokumentTypEnum,
        VERFUEGUNG: 'VERFUEGUNG' as DokumentTypEnum,
        VERORDNUNG: 'VERORDNUNG' as DokumentTypEnum,
        VERSICHERUNGSABSCHLUSS: 'VERSICHERUNGSABSCHLUSS' as DokumentTypEnum,
        VERTRAGSMUTATION: 'VERTRAGSMUTATION' as DokumentTypEnum
    };
}


