/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FranchiseSelbstbehaltPerYearVorversicherer } from './franchiseSelbstbehaltPerYearVorversicherer';
import { FranchiseSelbstbehaltProJahrKostenverteilung } from './franchiseSelbstbehaltProJahrKostenverteilung';

export interface FranchiseSelbstbehaltPerYear {
  /**
   * payed franchise / deductible CSS Versicherung
   */
  payedFranchise: number;
  /**
   * payed franchise / deductible plus former insurance
   */
  payedFranchiseTotal: number;
  /**
   * balance / Restbetrag for franchise / deductible (former insurance included)
   */
  franchiseBalance: number;
  /**
   * payed selbstbehalt / retention fee CSS Versicherung
   */
  payedSelbstbehalt: number;
  /**
   * payed selbstbehalt / retention fee plus former inscurance
   */
  payedSelbstbehaltTotal: number;
  /**
   * balance / Restbetrag for selbstbehalt / retention (former insurance included)
   */
  selbstbehaltBalance: number;
  franchiseSelbstbehaltPerYearBreakdownOfCosts?: FranchiseSelbstbehaltProJahrKostenverteilung;
  franchiseSelbstbehaltPerYearVorversicherer?: FranchiseSelbstbehaltPerYearVorversicherer;
  jahr?: number;
  vereinbarteFranchise?: number;
  vereinbarterSelbstbehalt?: number;
}

