/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FrvDeckung } from './frvDeckung';


export interface FrvProdukt { 
    /**
     * version of terms and conditions
     */
    avbVersion: string;
    /**
     * paket name as string in users portal language
     */
    produktLabel: string;
    /**
     * fachliche Schlüssel for this paket
     */
    produktNr: string;
    bruttoPraemie: number;
    /**
     * Zuschlag and Nachlass
     */
    zuNa: number;
    nettoPraemie: number;
    /**
     * ammount excluded ZuNa and StempelSteuer
     */
    dokumentenPraemie: number;
    /**
     * Deckungen of a Frv product
     */
    deckungen: Array<FrvDeckung>;
    paket?: boolean;
}

