/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GrundversicherungsTypWrapper {
  /**
   * GrunderversicherungsTyp / -Modell
   */
  grundversicherungsTyp?: GrundversicherungsTypWrapper.GrundversicherungsTypEnum;
  /**
   * Anbieter
   */
  anbieter?: GrundversicherungsTypWrapper.AnbieterEnum;
}

export namespace GrundversicherungsTypWrapper {
  export type GrundversicherungsTypEnum =
    'BILATERALE_VERTRAEGE'
    | 'BONUSVERSICHERUNG'
    | 'GESUNDHEITSPRAXISVERSICHERUNG'
    | 'HAUSARZTVERSICHERUNG'
    | 'MEDIZINISCHER_TELEFONDIENST'
    | 'MULTIMED'
    | 'SONSTIGE'
    | 'STANDARD';
  export const GrundversicherungsTypEnum = {
    BILATERALEVERTRAEGE: 'BILATERALE_VERTRAEGE' as GrundversicherungsTypEnum,
    BONUSVERSICHERUNG: 'BONUSVERSICHERUNG' as GrundversicherungsTypEnum,
    GESUNDHEITSPRAXISVERSICHERUNG: 'GESUNDHEITSPRAXISVERSICHERUNG' as GrundversicherungsTypEnum,
    HAUSARZTVERSICHERUNG: 'HAUSARZTVERSICHERUNG' as GrundversicherungsTypEnum,
    MEDIZINISCHERTELEFONDIENST: 'MEDIZINISCHER_TELEFONDIENST' as GrundversicherungsTypEnum,
    MULTIMED: 'MULTIMED' as GrundversicherungsTypEnum,
    SONSTIGE: 'SONSTIGE' as GrundversicherungsTypEnum,
    STANDARD: 'STANDARD' as GrundversicherungsTypEnum
  };
  export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
  export const AnbieterEnum = {
    ARCOSANA: 'ARCOSANA' as AnbieterEnum,
    AUXILIA: 'AUXILIA' as AnbieterEnum,
    CSS: 'CSS' as AnbieterEnum,
    INTRAS: 'INTRAS' as AnbieterEnum,
    SANAGATE: 'SANAGATE' as AnbieterEnum,
    ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
    ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
  };
}


