/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DokumentReferenz } from './dokumentReferenz';

export interface Lead {
  /**
   * id to link to the content in AEM
   */
  contentId: string;
  /**
   * date as String: yyyy-MM-dd
   */
  issueDate: string;
  dokumentReference?: DokumentReferenz;
  /**
   * true if read
   */
  read: boolean;
  /**
   * unique identifier in sending system
   */
  leadKey: string;
  leadType: Lead.LeadTypeEnum;
  /**
   * versicherte Person (insured person) intenal unique identifier
   */
  versichertePersonPartnerNr: string;
  /**
   * versicherte Person (insured person) User Id
   */
  versichertePersonUserId: string;
}
export namespace Lead {
    export type LeadTypeEnum = 'DOCUMENT' | 'MESSAGE';
    export const LeadTypeEnum = {
        DOCUMENT: 'DOCUMENT' as LeadTypeEnum,
        MESSAGE: 'MESSAGE' as LeadTypeEnum
    };
}


