/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Leistungsabrechnung { 
    /**
     * date as String: yyyy-MM-dd
     */
    abrechnungsDate?: string;
    /**
     * abrechnung unique identifier
     */
    abrechnungsNr: string;
    /**
     * sparte
     */
    sparte?: Leistungsabrechnung.SparteEnum;
    /**
     * status
     */
    ausgleichsStatus: Leistungsabrechnung.AusgleichsStatusEnum;
    ausgleichsStatusLabel?: string;
    /**
     * document identifier to load from resouce /dokumentenverwaltung
     */
    dokumentNr?: string;
    /**
     * size of the document
     */
    fileSize?: number;
    /**
     * File ending of the Document (could be used for Logo)
     */
    fileEnding?: string;
    /**
     * name of the file
     */
    fileName?: string;
    /**
     * amount which user will receive
     */
    yourCreditBalance?: number;
    /**
     * amount which has to be payed to the insurance company
     */
    insuranceCreditBalance?: number;
    /**
     * date as String: yyyy-MM-dd
     */
    dueDate: string;
    cssCreditBalance?: number;
}
export namespace Leistungsabrechnung {
    export type SparteEnum = 'KV' | 'FRV' | 'SPV' | 'SHV';
    export const SparteEnum = {
        KV: 'KV' as SparteEnum,
        FRV: 'FRV' as SparteEnum,
        SPV: 'SPV' as SparteEnum,
        SHV: 'SHV' as SparteEnum
    };
    export type AusgleichsStatusEnum = 'AUSGEGLICHEN' | 'OFFEN';
    export const AusgleichsStatusEnum = {
        AUSGEGLICHEN: 'AUSGEGLICHEN' as AusgleichsStatusEnum,
        OFFEN: 'OFFEN' as AusgleichsStatusEnum
    };
}


