/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferteAntragProdukt } from './offerteAntragProdukt';


/**
 * one of the offer\'s premium payers
 */
export interface OfferteAntragPraemienzahler { 
    /**
     * premium payer lastname firstname
     */
    pzNachnameVorname?: string;
    /**
     * total amount
     */
    subtotal: number;
    /**
     * products in offer
     */
    offerteAntragProdukt: Array<OfferteAntragProdukt>;
}

