/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferteAntragPraemienzahler } from './offerteAntragPraemienzahler';


/**
 * some basic offer data
 */
export interface Offer { 
    /**
     * total amount
     */
    amount: number;
    /**
     * versicherte Person (insured person) firstname lastname
     */
    versichertePersonNachnameVorname: string;
    /**
     * date as String: yyyy-MM-dd
     */
    createdAt: string;
    kanalLabel: string;
    /**
     * sales channel
     */
    kanal?: Offer.KanalEnum;
    /**
     * unique identifier
     */
    oaNr: string;
    /**
     * date as String: yyyy-MM-dd
     */
    versicherungsbeginn: string;
    bezugspersonPartnerNr: string;
    /**
     * document identifier to load from resouce /dokumentenverwaltung
     */
    dokumentNr?: string;
    /**
     * date as String: yyyy-MM-dd
     */
    validFrom: string;
    anbieterLabel: string;
    /**
     * anbieter / provider, like CSS or ARCOSANA
     */
    anbieter: Offer.AnbieterEnum;
    /**
     * one or more premium payer with his / her products
     */
    offerteAntragPraemienzahler: Array<OfferteAntragPraemienzahler>;
}
export namespace Offer {
    export type KanalEnum = 'AM_SCHALTER' | 'BEIM_KUNDEN' | 'BRIEF' | 'EMAIL_INTERNET' | 'EOS' | 'EREIGMA' | 'FAX' | 'GESUNDHEITSEVENT' | 'MESSEN_ANDERE_EVENTS' | 'MYCSS' | 'OVERFLOW_TELEFON' | 'PEX' | 'PRAEMIENRECHNER' | 'SYSTEM' | 'TELEFON' | 'VERGLEICHSDIENST' | 'VOICEMAIL_TELEFON';
    export const KanalEnum = {
        AMSCHALTER: 'AM_SCHALTER' as KanalEnum,
        BEIMKUNDEN: 'BEIM_KUNDEN' as KanalEnum,
        BRIEF: 'BRIEF' as KanalEnum,
        EMAILINTERNET: 'EMAIL_INTERNET' as KanalEnum,
        EOS: 'EOS' as KanalEnum,
        EREIGMA: 'EREIGMA' as KanalEnum,
        FAX: 'FAX' as KanalEnum,
        GESUNDHEITSEVENT: 'GESUNDHEITSEVENT' as KanalEnum,
        MESSENANDEREEVENTS: 'MESSEN_ANDERE_EVENTS' as KanalEnum,
        MYCSS: 'MYCSS' as KanalEnum,
        OVERFLOWTELEFON: 'OVERFLOW_TELEFON' as KanalEnum,
        PEX: 'PEX' as KanalEnum,
        PRAEMIENRECHNER: 'PRAEMIENRECHNER' as KanalEnum,
        SYSTEM: 'SYSTEM' as KanalEnum,
        TELEFON: 'TELEFON' as KanalEnum,
        VERGLEICHSDIENST: 'VERGLEICHSDIENST' as KanalEnum,
        VOICEMAILTELEFON: 'VOICEMAIL_TELEFON' as KanalEnum
    };
    export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
    export const AnbieterEnum = {
        ARCOSANA: 'ARCOSANA' as AnbieterEnum,
        AUXILIA: 'AUXILIA' as AnbieterEnum,
        CSS: 'CSS' as AnbieterEnum,
        INTRAS: 'INTRAS' as AnbieterEnum,
        SANAGATE: 'SANAGATE' as AnbieterEnum,
        ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
        ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
    };
}


