/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZahlungsverbindungenVerwendungszweckObject } from './zahlungsverbindungenVerwendungszweckObject';

/**
 * Payment account
 */
export interface PaymentAccount {
  anbieterLabels?: Array<string>;
  /**
   * list of anbieter / provider, i.e. ARCOSANA and / or CSS. Full list see swagger.json
   */
  anbieter?: Array<PaymentAccount.AnbieterEnum>;
  /**
   * date as String: yyyy-MM-dd
   */
  validFrom?: string;
  /**
   * list of usages, e.g. LEISTUNGSEMPFAENGER / LSV_DD (partner receives benefits, payment automatically charged)
   */
  verwendungsZwecke?: Array<ZahlungsverbindungenVerwendungszweckObject>;
  zahlwegLabel?: string;
  /**
   * direction of money flow: customer reiceives money (VERGUETUNG) or has to pay money (BELASTUNG) or both with one account (VERGUETUNGUNDBELASTUNG)
   */
  zahlweg: PaymentAccount.ZahlwegEnum;
  accountClazz?: string;
}
export namespace PaymentAccount {
    export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
    export const AnbieterEnum = {
        ARCOSANA: 'ARCOSANA' as AnbieterEnum,
        AUXILIA: 'AUXILIA' as AnbieterEnum,
        CSS: 'CSS' as AnbieterEnum,
        INTRAS: 'INTRAS' as AnbieterEnum,
        SANAGATE: 'SANAGATE' as AnbieterEnum,
        ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
        ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
    };
    export type ZahlwegEnum = 'BELASTUNGEN' | 'VERGUETUNGEN' | 'VERGUETUNGENUNDBELASTUNGEN';
    export const ZahlwegEnum = {
        BELASTUNGEN: 'BELASTUNGEN' as ZahlwegEnum,
        VERGUETUNGEN: 'VERGUETUNGEN' as ZahlwegEnum,
        VERGUETUNGENUNDBELASTUNGEN: 'VERGUETUNGENUNDBELASTUNGEN' as ZahlwegEnum
    };
}


