/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicePraemienzahler } from './policePraemienzahler';


/**
 * A policy
 */
export interface Policy { 
    /**
     * Policy unique identifier
     */
    policenNr: string;
    /**
     * versicherte Person (insured person) PartnerNr / internal unique identifier
     */
    versichertePersonPartnerNr: string;
    /**
     * document identifier to load from resouce /dokumentenverwaltung
     */
    dokumentNr?: string;
    /**
     * date as String: yyyy-MM-dd
     */
    createdAt: string;
    /**
     * date as String: yyyy-MM-dd
     */
    validFrom: string;
    /**
     * date as String: yyyy-MM-dd
     */
    validTo: string;
    anbieterLabel?: string;
    /**
     * anbieter / provider, like CSS or ARCOSANA
     */
    anbieter: Policy.AnbieterEnum;
    erstellungsgrundLabel?: string;
    /**
     * reason for issue
     */
    erstellungsgrund?: Policy.ErstellungsgrundEnum;
    /**
     * total montly premium
     */
    total: number;
    /**
     * products with their praemienzahler / premium payer
     */
    policePraemienzahler: Array<PolicePraemienzahler>;
    versichertepersonVornameNachname?: string;
}
export namespace Policy {
    export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
    export const AnbieterEnum = {
        ARCOSANA: 'ARCOSANA' as AnbieterEnum,
        AUXILIA: 'AUXILIA' as AnbieterEnum,
        CSS: 'CSS' as AnbieterEnum,
        INTRAS: 'INTRAS' as AnbieterEnum,
        SANAGATE: 'SANAGATE' as AnbieterEnum,
        ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
        ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
    };
    export type ErstellungsgrundEnum = 'AENDERUNG_GRUNDVERSICHERUNG' | 'AENDERUNG_PRAEMIENVERBILLIGUNG' | 'AENDERUNG_RABATT' | 'AENDERUNG_RAHMENVERTRAG' | 'AENDERUNG_TG_INFOLGE_AHV_ALTER' | 'AENDERUNG_VERSICHERUNGSDECKUNG' | 'AENDERUNG_VERSICHERUNGSORT' | 'AENDERUNG_VERTRAGSROLLE' | 'AENDERUNG_VN' | 'AENDERUNG_WOHNGEMEINDE' | 'AENDERUNG_ZAHLUNGSVERBINDUNG' | 'AGENTURWECHSEL' | 'ALLG_PRAEMIENANPASSUNG' | 'ANNULLATION_SISTIERUNG_AUSLAND' | 'AUFHEBUNG_LEISTUNGSAUSSCHLUSS_EINSCHR' | 'AUFHEBUNG_SISTIERUNG_AUSLAND' | 'AUFHEBUNG_SISTIERUNG_GRUNDVERS' | 'AUSSCHLUSS_PERSON' | 'DATENUEBERNAHME' | 'DEF_LSDEKL' | 'DUBLETTEN_ZUSAMMENLEGUNG' | 'EINSCHLUSS_PERSON' | 'ERNEUERUNG' | 'FUSION_AGENTUR' | 'GEMEINDEFUSION_MIT_PRAEMIENAENDERUNG' | 'GEMEINDEFUSION_OHNE_PRAEMIENAENDERUNG' | 'KORREKTUR_VERSICHERUNGSDECKUNG' | 'NEUABSCHLUSS' | 'RECHNUNG_NICHT_BEZAHLT' | 'SANIERUNG' | 'SISTIERUNG_AUSLAND' | 'SISTIERUNG_GRUNDVERS' | 'STANDARD' | 'TARIFANPASSUNG' | 'UNFALLEINSCHLUSS_64_65' | 'VERSAENDERUNG_GEM_VERSANTRAG' | 'VERTRAGSAENDERUNG' | 'WECHSEL_CSS_GRUPPE' | 'WEITERFUEHRUNG_POLICE' | 'WIEDEREINTRITT' | 'ZAHLUNG_ERFOLGT';
    export const ErstellungsgrundEnum = {
        AENDERUNGGRUNDVERSICHERUNG: 'AENDERUNG_GRUNDVERSICHERUNG' as ErstellungsgrundEnum,
        AENDERUNGPRAEMIENVERBILLIGUNG: 'AENDERUNG_PRAEMIENVERBILLIGUNG' as ErstellungsgrundEnum,
        AENDERUNGRABATT: 'AENDERUNG_RABATT' as ErstellungsgrundEnum,
        AENDERUNGRAHMENVERTRAG: 'AENDERUNG_RAHMENVERTRAG' as ErstellungsgrundEnum,
        AENDERUNGTGINFOLGEAHVALTER: 'AENDERUNG_TG_INFOLGE_AHV_ALTER' as ErstellungsgrundEnum,
        AENDERUNGVERSICHERUNGSDECKUNG: 'AENDERUNG_VERSICHERUNGSDECKUNG' as ErstellungsgrundEnum,
        AENDERUNGVERSICHERUNGSORT: 'AENDERUNG_VERSICHERUNGSORT' as ErstellungsgrundEnum,
        AENDERUNGVERTRAGSROLLE: 'AENDERUNG_VERTRAGSROLLE' as ErstellungsgrundEnum,
        AENDERUNGVN: 'AENDERUNG_VN' as ErstellungsgrundEnum,
        AENDERUNGWOHNGEMEINDE: 'AENDERUNG_WOHNGEMEINDE' as ErstellungsgrundEnum,
        AENDERUNGZAHLUNGSVERBINDUNG: 'AENDERUNG_ZAHLUNGSVERBINDUNG' as ErstellungsgrundEnum,
        AGENTURWECHSEL: 'AGENTURWECHSEL' as ErstellungsgrundEnum,
        ALLGPRAEMIENANPASSUNG: 'ALLG_PRAEMIENANPASSUNG' as ErstellungsgrundEnum,
        ANNULLATIONSISTIERUNGAUSLAND: 'ANNULLATION_SISTIERUNG_AUSLAND' as ErstellungsgrundEnum,
        AUFHEBUNGLEISTUNGSAUSSCHLUSSEINSCHR: 'AUFHEBUNG_LEISTUNGSAUSSCHLUSS_EINSCHR' as ErstellungsgrundEnum,
        AUFHEBUNGSISTIERUNGAUSLAND: 'AUFHEBUNG_SISTIERUNG_AUSLAND' as ErstellungsgrundEnum,
        AUFHEBUNGSISTIERUNGGRUNDVERS: 'AUFHEBUNG_SISTIERUNG_GRUNDVERS' as ErstellungsgrundEnum,
        AUSSCHLUSSPERSON: 'AUSSCHLUSS_PERSON' as ErstellungsgrundEnum,
        DATENUEBERNAHME: 'DATENUEBERNAHME' as ErstellungsgrundEnum,
        DEFLSDEKL: 'DEF_LSDEKL' as ErstellungsgrundEnum,
        DUBLETTENZUSAMMENLEGUNG: 'DUBLETTEN_ZUSAMMENLEGUNG' as ErstellungsgrundEnum,
        EINSCHLUSSPERSON: 'EINSCHLUSS_PERSON' as ErstellungsgrundEnum,
        ERNEUERUNG: 'ERNEUERUNG' as ErstellungsgrundEnum,
        FUSIONAGENTUR: 'FUSION_AGENTUR' as ErstellungsgrundEnum,
        GEMEINDEFUSIONMITPRAEMIENAENDERUNG: 'GEMEINDEFUSION_MIT_PRAEMIENAENDERUNG' as ErstellungsgrundEnum,
        GEMEINDEFUSIONOHNEPRAEMIENAENDERUNG: 'GEMEINDEFUSION_OHNE_PRAEMIENAENDERUNG' as ErstellungsgrundEnum,
        KORREKTURVERSICHERUNGSDECKUNG: 'KORREKTUR_VERSICHERUNGSDECKUNG' as ErstellungsgrundEnum,
        NEUABSCHLUSS: 'NEUABSCHLUSS' as ErstellungsgrundEnum,
        RECHNUNGNICHTBEZAHLT: 'RECHNUNG_NICHT_BEZAHLT' as ErstellungsgrundEnum,
        SANIERUNG: 'SANIERUNG' as ErstellungsgrundEnum,
        SISTIERUNGAUSLAND: 'SISTIERUNG_AUSLAND' as ErstellungsgrundEnum,
        SISTIERUNGGRUNDVERS: 'SISTIERUNG_GRUNDVERS' as ErstellungsgrundEnum,
        STANDARD: 'STANDARD' as ErstellungsgrundEnum,
        TARIFANPASSUNG: 'TARIFANPASSUNG' as ErstellungsgrundEnum,
        UNFALLEINSCHLUSS6465: 'UNFALLEINSCHLUSS_64_65' as ErstellungsgrundEnum,
        VERSAENDERUNGGEMVERSANTRAG: 'VERSAENDERUNG_GEM_VERSANTRAG' as ErstellungsgrundEnum,
        VERTRAGSAENDERUNG: 'VERTRAGSAENDERUNG' as ErstellungsgrundEnum,
        WECHSELCSSGRUPPE: 'WECHSEL_CSS_GRUPPE' as ErstellungsgrundEnum,
        WEITERFUEHRUNGPOLICE: 'WEITERFUEHRUNG_POLICE' as ErstellungsgrundEnum,
        WIEDEREINTRITT: 'WIEDEREINTRITT' as ErstellungsgrundEnum,
        ZAHLUNGERFOLGT: 'ZAHLUNG_ERFOLGT' as ErstellungsgrundEnum
    };
}


