/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Praemienabrechnung { 
    /**
     * abrechnung unique identifier
     */
    abrechnungsNr?: string;
    /**
     * sparte
     */
    sparte?: Praemienabrechnung.SparteEnum;
    /**
     * status
     */
    ausgleichsStatus: Praemienabrechnung.AusgleichsStatusEnum;
    /**
     * total amount
     */
    amount?: number;
    /**
     * true if document is available over dokumentenverwaltung resource
     */
    dokumentAvailable?: boolean;
    /**
     * document identifier to load from resouce /dokumentenverwaltung
     */
    dokumentNr?: string;
    /**
     * size of the document
     */
    fileSize?: number;
    /**
     * File ending of the Document (could be used for Logo)
     */
    fileEnding?: string;
    /**
     * name of the file
     */
    fileName?: string;
    /**
     * unique identifier for versicherte person
     */
    partnerNr: string;
    /**
     * date as String: yyyy-MM-dd
     */
    rechnungsDate: string;
    /**
     * date as String: yyyy-MM-dd
     */
    rechnungsPeriodeTo: string;
    /**
     * date as String: yyyy-MM-dd
     */
    rechnungsPeriodeFrom: string;
    /**
     * date as String: yyyy-MM-dd
     */
    dueDate: string;
    /**
     * date as String: yyyy-MM-dd
     */
    payedDate: string;
    /**
     * payment method: E_RECHNUNG is available for abrechnung newer 2017_R2 only
     */
    zahlweg: Praemienabrechnung.ZahlwegEnum;
    /**
     * hint for document availablity: show download link or tooltip
     */
    documentAvailability: Praemienabrechnung.DocumentAvailabilityEnum;
}
export namespace Praemienabrechnung {
    export type SparteEnum = 'KV' | 'FRV' | 'SPV' | 'SHV';
    export const SparteEnum = {
        KV: 'KV' as SparteEnum,
        FRV: 'FRV' as SparteEnum,
        SPV: 'SPV' as SparteEnum,
        SHV: 'SHV' as SparteEnum
    };
    export type AusgleichsStatusEnum = 'AUSGEGLICHEN' | 'OFFEN';
    export const AusgleichsStatusEnum = {
        AUSGEGLICHEN: 'AUSGEGLICHEN' as AusgleichsStatusEnum,
        OFFEN: 'OFFEN' as AusgleichsStatusEnum
    };
    export type ZahlwegEnum = 'ESR' | 'E_RECHNUNG' | 'LSV';
    export const ZahlwegEnum = {
        ESR: 'ESR' as ZahlwegEnum,
        ERECHNUNG: 'E_RECHNUNG' as ZahlwegEnum,
        LSV: 'LSV' as ZahlwegEnum
    };
    export type DocumentAvailabilityEnum = 'NO_DOC_LSV' | 'RETRY_LATER' | 'DOWNLOAD';
    export const DocumentAvailabilityEnum = {
        NODOCLSV: 'NO_DOC_LSV' as DocumentAvailabilityEnum,
        RETRYLATER: 'RETRY_LATER' as DocumentAvailabilityEnum,
        DOWNLOAD: 'DOWNLOAD' as DocumentAvailabilityEnum
    };
}


