/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProduktbezeichnungAnfrageIn { 
    anbieterLabel: string;
    /**
     * anbieter / provider, like CSS or ARCOSANA
     */
    anbieter: ProduktbezeichnungAnfrageIn.AnbieterEnum;
    /**
     * version of terms and conditions
     */
    avbVersion?: string;
    /**
     * level
     */
    ebene: ProduktbezeichnungAnfrageIn.EbeneEnum;
    /**
     * unique identifier
     */
    fachschluessel: string;
}
export namespace ProduktbezeichnungAnfrageIn {
    export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
    export const AnbieterEnum = {
        ARCOSANA: 'ARCOSANA' as AnbieterEnum,
        AUXILIA: 'AUXILIA' as AnbieterEnum,
        CSS: 'CSS' as AnbieterEnum,
        INTRAS: 'INTRAS' as AnbieterEnum,
        SANAGATE: 'SANAGATE' as AnbieterEnum,
        ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
        ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
    };
    export type EbeneEnum = 'ELEMENTAR_PRODUKT' | 'PRODUKT' | 'VERKAUFS_PRODUKT';
    export const EbeneEnum = {
        ELEMENTARPRODUKT: 'ELEMENTAR_PRODUKT' as EbeneEnum,
        PRODUKT: 'PRODUKT' as EbeneEnum,
        VERKAUFSPRODUKT: 'VERKAUFS_PRODUKT' as EbeneEnum
    };
}


