/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Rolle { 
    /**
     * date as String: yyyy-MM-dd
     */
    validTo: string;
    /**
     * KE: correspondence recipient, LE: benefit recepient, PZ: premium payer
     */
    type: Rolle.TypeEnum;
    /**
     * date as String: yyyy-MM-dd
     */
    validFrom: string;
}
export namespace Rolle {
    export type TypeEnum = 'LEISTUNGSEMPFAENGER' | 'KORRESPONDENZEMPFAENGER' | 'PRAEMIENZAHLER';
    export const TypeEnum = {
        LEISTUNGSEMPFAENGER: 'LEISTUNGSEMPFAENGER' as TypeEnum,
        KORRESPONDENZEMPFAENGER: 'KORRESPONDENZEMPFAENGER' as TypeEnum,
        PRAEMIENZAHLER: 'PRAEMIENZAHLER' as TypeEnum
    };
}


