/**
 * CSS customer portal API: Vertrag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShvDeckung { 
    /**
     * Familie, Mieter
     */
    deckungsLabel: Array<string>;
    bruttoPraemie: number;
    versicherungssumme?: number;
    anzahl?: number;
    leistungsvariante?: string;
}

