/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparteTranslated } from './sparteTranslated';

export interface SpartenWrapper {
  /**
   * ordered Sparten contained in unfiltered LEAs if any with label / translation
   */
  sparten?: Array<SparteTranslated>;
  /**
   * true if contained status is KV only
   */
  hasKvOnly: boolean;
}

