/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Steuerauszug { 
    anbieterLabel: string;
    /**
     * anbieter / provider, like CSS or ARCOSANA
     */
    anbieter: Steuerauszug.AnbieterEnum;
    documentSizeInBytes: number;
    /**
     * document identifier to load from resouce /dokumentenverwaltung
     */
    dokumentNr: string;
    /**
     * every tax statement is valid for a certain year
     */
    year: number;
}
export namespace Steuerauszug {
    export type AnbieterEnum = 'ARCOSANA' | 'AUXILIA' | 'CSS' | 'INTRAS' | 'SANAGATE' | 'ZURICH_CONNECT' | 'ZURICH_LEBEN';
    export const AnbieterEnum = {
        ARCOSANA: 'ARCOSANA' as AnbieterEnum,
        AUXILIA: 'AUXILIA' as AnbieterEnum,
        CSS: 'CSS' as AnbieterEnum,
        INTRAS: 'INTRAS' as AnbieterEnum,
        SANAGATE: 'SANAGATE' as AnbieterEnum,
        ZURICHCONNECT: 'ZURICH_CONNECT' as AnbieterEnum,
        ZURICHLEBEN: 'ZURICH_LEBEN' as AnbieterEnum
    };
}


