/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the person, who is logged in the portal system
 */
export interface UnauthorizedPersonAllOf { 
    /**
     * terms and conditions (nvb) accepted
     */
    nvbAccepted: boolean;
    anredeLabel?: string;
    /**
     * salutation
     */
    anrede?: UnauthorizedPersonAllOf.AnredeEnum;
    /**
     * e.g. PhD
     */
    titel?: string;
    /**
     * firstname
     */
    vorname?: string;
    /**
     * lastname
     */
    nachname?: string;
}
export namespace UnauthorizedPersonAllOf {
    export type AnredeEnum = 'FRAEULEIN' | 'FRAU' | 'HERR';
    export const AnredeEnum = {
        FRAEULEIN: 'FRAEULEIN' as AnredeEnum,
        FRAU: 'FRAU' as AnredeEnum,
        HERR: 'HERR' as AnredeEnum
    };
}


