/**
 * CSS customer portal API
 * This API provides access to the customer data of any CSS customer with myCSS / mySanagate access
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support.e-business.portal@css.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZahlungsverbindungenVerwendungszweckObject { 
    verwendungsZweckLabel?: string;
    /**
     * e.g. for benefits, premium, ...
     */
    verwendungsZweck: ZahlungsverbindungenVerwendungszweckObject.VerwendungsZweckEnum;
    zahlwegBelastungLabel?: string;
    /**
     * how money is charged by the bank (payment slip, automatically, ...)
     */
    zahlwegBelastung?: ZahlungsverbindungenVerwendungszweckObject.ZahlwegBelastungEnum;
}
export namespace ZahlungsverbindungenVerwendungszweckObject {
    export type VerwendungsZweckEnum = 'ENTSCHAEDIGUNGSEMPFAENGER' | 'LEISTUNGSEMPFAENGER' | 'LEISTUNGSEMPFAENGER_KTG_KUTG' | 'LEISTUNGSERBRINGER' | 'PRAEMIENZAHLER' | 'RECHNUNGSSTELLER' | 'V6UG';
    export const VerwendungsZweckEnum = {
        ENTSCHAEDIGUNGSEMPFAENGER: 'ENTSCHAEDIGUNGSEMPFAENGER' as VerwendungsZweckEnum,
        LEISTUNGSEMPFAENGER: 'LEISTUNGSEMPFAENGER' as VerwendungsZweckEnum,
        LEISTUNGSEMPFAENGERKTGKUTG: 'LEISTUNGSEMPFAENGER_KTG_KUTG' as VerwendungsZweckEnum,
        LEISTUNGSERBRINGER: 'LEISTUNGSERBRINGER' as VerwendungsZweckEnum,
        PRAEMIENZAHLER: 'PRAEMIENZAHLER' as VerwendungsZweckEnum,
        RECHNUNGSSTELLER: 'RECHNUNGSSTELLER' as VerwendungsZweckEnum,
        V6UG: 'V6UG' as VerwendungsZweckEnum
    };
    export type ZahlwegBelastungEnum = 'ESR' | 'ESR_PROF_DEF' | 'E_RECHNUNG' | 'KEINE_AUSZAHLUNG' | 'KEINE_BELASTUNG' | 'KEIN_AUSZAHLUNGSWEG_BEKANNT' | 'KREDITKARTE' | 'LSV_DD' | 'POST_BANKZAHLUNG' | 'ZAHLUNGSANWEISUNG';
    export const ZahlwegBelastungEnum = {
        ESR: 'ESR' as ZahlwegBelastungEnum,
        ESRPROFDEF: 'ESR_PROF_DEF' as ZahlwegBelastungEnum,
        ERECHNUNG: 'E_RECHNUNG' as ZahlwegBelastungEnum,
        KEINEAUSZAHLUNG: 'KEINE_AUSZAHLUNG' as ZahlwegBelastungEnum,
        KEINEBELASTUNG: 'KEINE_BELASTUNG' as ZahlwegBelastungEnum,
        KEINAUSZAHLUNGSWEGBEKANNT: 'KEIN_AUSZAHLUNGSWEG_BEKANNT' as ZahlwegBelastungEnum,
        KREDITKARTE: 'KREDITKARTE' as ZahlwegBelastungEnum,
        LSVDD: 'LSV_DD' as ZahlwegBelastungEnum,
        POSTBANKZAHLUNG: 'POST_BANKZAHLUNG' as ZahlwegBelastungEnum,
        ZAHLUNGSANWEISUNG: 'ZAHLUNGSANWEISUNG' as ZahlwegBelastungEnum
    };
}


